### PR TITLE
Creating list of code owners

### PR DESCRIPTION
**Pull request by castelao**
This list was defined by @vturpin based on the original authors of OG-1.0 to speed up the approval procedure of final adjustments and corrections.

### CODE REVIEW

**Comment by castelao** [comment]
@vturpin , please double-check the list, please. For the ones that I knew, I changed the email by the Github's handle. Once this is approved and merged, I can move forward with the repository setup.

**Comment by castelao** [comment]
To give some context to the community, this is part of some changes to speed up the procedure to apply changes, improvements, and corrections.

**Comment by soerenthomsen** [comment]
Thierry Carval (@tcarval) and John Kerfoot (@kerfoot) are on GitHub

**Review by vturpin — APPROVED** [review]

**Review by vturpin — APPROVED** [review]

**Review by vturpin — COMMENTED** [review]
This pull request is not needed anymore, am I right ?

**Comment by castelao** [comment]
@vturpin , I didn't understand why it wouldn't be required anymore.

**Review by glidermann — APPROVED** [review]

**Comment by vturpin** [comment]
@castelao sorry, forget about my comment. that's fine.

**Comment by vturpin** [comment]
Two authors approved the changes, so I merged. Hopefully this is fine.

**Pull request merged**
