### PR TITLE
SENSOR_CALIBRATION_* variables

### PR DESCRIPTION
**Pull request by JuangaSocib**
#45 Adding 3 variables and a new dimension to represent sensor calibrations.

### CODE REVIEW

**Comment by soerenthomsen** [comment]
Thanks @JuangaSocib for making the PR! Glad to see that the GitHub activity is kicking off

**Comment by vturpin** [comment]
I like the SENSOR_CALIB_LINK variable. I think it is very relevant for delayed mode in particular. Also because it is lot of work to put sensor calibrations coefficient into the files. 

I do really understand the need of "SENSOR_CALIB_SENSOR". Could you suggest an exemple please ?

**Comment by callumrollo** [comment]
I agree that adding calibration coefficients is laborious, but I'm not sure that linking to calibration sheets is a reliable solution. How do you ensure that the links to the documents remains valid? Where would these calibrations be uploaded to?

**Comment by justinbuck** [comment]
@callumrollo we need to assign a persistent identifier (PID) such as a DOI to the calibration sheet and reference the PID which will always resolve back to a landing page.

**Comment by callumrollo** [comment]
New cdl looks good! Just to check, is the extra dimension N_CALIB necessary? If all sensors have calibrations (which they should) wouldn't N_CALIB = N_SENSOR?

**Comment by JuangaSocib** [comment]
Calibration sheets may not be available for all sensors, or the organization in charge may not be able to assign a PID at the time of dataset publication. This aspect could be measured through the appropriate metric and see if support is necessary in this regard.

**Review by vturpin — APPROVED** [review]

**Review by vturpin — APPROVED** [review]

**Review by vturpin — DISMISSED** [review]

**Comment by vturpin** [comment]
I now understand that N_calib is usefull to reduce le length of SENSOR_CALIBRATION_SENSOR, SENSOR_CALIBRATION_DATE and SENSOR_CALIBRATION_LINK
That's fine to me ! 

-  SENSOR = "CTD_PRES", "CTD_TEMP", "CTD_CNDC", "FLUOROMETER_CHLA", 
-     "OPTODE_DOXY" ;
-  SENSOR_SERIAL_NUMBER = "11111", "22222", "33333", "44444", "55555" ;
-  SENSOR_CALIBRATION_DATE = "2018-12-01T11:00:00Z" ;
-  SENSOR_CALIBRATION_SENSOR = "22222" ;
-  SENSOR_CALIBRATION_LINK = "https://doi.org/xx.yyyy/12345" ;

**Review by vturpin — APPROVED** [review]

**Comment by castelao** [comment]
@JuangaSocib , what do you think about the solution proposed on #103 instead? Having each sensor as a group would move all those calibration and specification metadata to that group, organizing the information.

**Comment by JuangaSocib** [comment]
Hi @castelao, I agree that groups will improve the structure of the format. I will iterate in the #103 thread and when accepted I will update this one accordingly.

**Review by castelao — CHANGES_REQUESTED** [review]
@JuangaSocib , just to avoid any confusion, I'll block this PR until we get a conclusion on #103. My understanding is that you're in favor of that solution. Please let me know if I got it wrong. Thanks,

**Comment by castelao** [comment]
Was this deprecated with the approval of #103?

@JuangaSocib , is it OK to close this PR?

**Pull request closed without merging**
