### PR TITLE
A few corrections and inconsistencies found on the first prototype

### PR DESCRIPTION
**Pull request by castelao**
All these issues were identified by @soerenthomsen while reviewing #35 (first prototype). Thanks, @soerenthomsen !

### CODE REVIEW

**Review by justinbuck — APPROVED** [review]
The updated limits look good

**Review by vturpin — APPROVED** [review]

**Comment by vturpin** [comment]
2 approval, how do we merge now ?

**Comment by soerenthomsen** [comment]
it is still a "draft" at the moment. Draft's cannot be merged. Only @castelao can change this I think?

**Comment by castelao** [comment]
Thanks for your efficiency! I'm sorry that I'm not moving as fast as you. I still have a couple of notes to add to this one.

**Review by justinbuck — APPROVED** [review]
minor corrections

**Comment by glidermann** [comment]
Why is FillValue for TIME -1.0 but everywhere else -9999.9?

**Comment by justinbuck** [comment]
@glidermann  Fill value can be different for different variables because they have different physical ranges, it can be -1 for time because there are no ocean glider data prior to 1970, he key thing is that the fill value is listed against each variable.

**Comment by glidermann** [comment]
Thanks @justinbuck understand that, but just wondering why bother using different values? There was also no glider data before -9999.9 days before 1970 :) not a big deal, just curious!

**Comment by justinbuck** [comment]
It goes back to when we were storing data in single precision channels where we had to chose different values to stay within single precision limits. We tend to use double precision nowadays for most things so the limits are much greater.

**Review by glidermann — APPROVED** [review]

**Comment by vturpin** [comment]
@soerenthomsen When I try to resolve the conflict I found this : 
<<<<<<< fix/soeren_review
LATITUDE_GPS:units = “decimal degree north”;
=======
LATITUDE_GPS:standard_name = “latitude”;

LATITUDE_GPS:unit = “decimal degree north”;
>>>>>>> main
 (Same for Longitude).

It changes"unit" into "units" which is good. 
But it also remove "standard_name" for "latitude" and "longitude" ?
If yes, I don't understand why. That may be not on purpose.
If no, we will keep LATITUDE_GPS:standard_name = "latitude"; in the decription.
What do you think?

**Comment by justinbuck** [comment]
Hi @soerenthomsen we need to keep the standard names, there was another pull to add them in, so it maybe a midair collision. Justin

**Comment by castelao** [comment]
- @glidermann and @justinbuck discussion raised an interesting point. Technically the `FillValue` could be anything, as long as it is available and has the same data type of the variable it refers to. Despite that, we have to pick a value to illustrate it, but might be a good thing to add explicitly in the documentation that the user is allowed to choose their `FillValue`. For instance, I use `NaN` on Spray data.

- The conflict was because this branch was initiated before the standard_name was added. I think that I added that myself in another branch, I don't remember. Anyways, I just rebased this branch to include that and resolve the conflict.

- Another point here is the units for coordinates. It looks like the`decimal degree *` doesn't conform with [CF's recommendation](https://cfconventions.org/Data/cf-conventions/cf-conventions-1.9/cf-conventions.html#latitude-coordinate), but it should be instead `degrees_north`, for example.

This PR has the review approvals already, but since I did some modifications after the approvals, including the units, I'll wait at least another day to give the chance for any comments against it.

**Review by glidermann — CHANGES_REQUESTED** [review]
_GPS units should be "degrees_north" not "degree_north" This is how it is used for the plain variables like LATITUDE and complies with CF.

**Review by vturpin — APPROVED** [review]

**Comment by kerfoot** [comment]
Just an FYI that both degree_north and degrees_north are recognized as valid udunits2 units.  So either can be used but we should pick one and use it for all relevant variables.

**Review by justinbuck — APPROVED** [review]
Leads meeting 14th June 2022, updates to floats, case of GPS and alignment with CF

**Review by glidermann — APPROVED** [review]

**Pull request merged**
