### PR TITLE
Some suggestions on governance

### PR DESCRIPTION
**Pull request by castelao**
Some suggestions on the governance document created by @justinbuck .

### CODE REVIEW

**Comment by castelao** [comment]
@justinbuck , I have more suggestions, but I don't want to hold you longer. If I have a chance, I'll add more or create another PR.

**Review by vturpin — APPROVED** [review]

**Comment by castelao** [comment]
Usually, one approval would be enough to merge, but it would be best to get @justinbuck 's approval before merging on his work.

**Review by justinbuck — APPROVED** [review]
Happy for the proposed approach to iterate towards a consensus

**Comment by castelao** [comment]
I'm sorry. Some of my original suggestions I moved out to independent PRs, so this one here doesn't make much sense anymore as it is. But I still have a couple of suggestions that I'll add here shortly.

**Pull request merged**
