### PR TITLE
naming authority

### PR DESCRIPTION
**Pull request by castelao**
It's a free field as long as it is unique, but ACDD recommends using reverse-DNS. Adding an example.

### CODE REVIEW

**Review by soerenthomsen — COMMENTED** [review]
I don't feel like having the expertise to approve this pull-request i.e. as I don't know what ACDD-1.3 or reverse-DNS stands for. So I suggest we wait until @vturpin is back.

In general is will be helpful to have all acronyms listed in a glossary to make this document more useful for new users.

**Comment by castelao** [comment]
This is not a requirement but a recommendation from ACDD, so the other ones are not wrong and all that I'm doing here is adding an example that follows ACDD-1.3 suggested pattern.

@glidermann or @justinbuck , do you agree with this example?

**Review by justinbuck — APPROVED** [review]
Aligning with ACDD is a good thing, approved

**Comment by soerenthomsen** [comment]
Just double checking: @vturpin did you want to "merge" this PR or "close" it without implementing? 

If you want to merge you can reopen and merge after.

**Comment by vturpin** [comment]
I think I wanted to implement it... Shall I reopen ?

**Comment by soerenthomsen** [comment]
I reopen it!

**Comment by castelao** [comment]
I agree with you @soerenthomsen ! I worked yesterday with @vturpin on this one.

**Pull request merged**
