### PR TITLE
NETCDF4.adoc

### PR DESCRIPTION
**Pull request by vturpin**

### CODE REVIEW

**Comment by castelao** [comment]
@vturpin , I don't think we need to restrict to NetCDF-4. We made choices that made netCDF-3 incompatible, but let's assume a future version of netCDF that is backward compatible. Why not allow that as well?

My suggestion is to limit on defining NetCDF format standard.

**Comment by castelao** [comment]
Let's avoid duplicates and continue the discussion on #29. Once we get a consensus we can return here and apply the decision.

**Review by castelao — CHANGES_REQUESTED** [review]
Let's close the discussion on #29 with an agreement over there before any decision here.

**Review by justinbuck — APPROVED** [review]
This reflects discussion

**Review by glidermann — COMMENTED** [review]
I understand this to be an old request since the new text mentions NetCDF4. I have approved the text below by @justinbuck which mentions only NetCDF and clarifies incompatibility of NetCDF-3. How do we "reject" this change request?

**Comment by vturpin** [comment]
@castelao I think this is on you hand. I resolve the conflict, but can not merge. Could you help ?

**Review by castelao — APPROVED** [review]

**Comment by castelao** [comment]
I'm sorry that I was holding this one.

@justinbuck , thanks for text editing!

**Pull request merged**
