### PR TITLE
Missing Emma in the code reviewers.

### PR DESCRIPTION
**Pull request by castelao**
Proponents: 
Moderator: @OceanGlidersCommunity/format-mantainers

# Type of PR

- [ ] Typo without possible change of interpretation of the related text.
- [ ] Fix of some error, inconsistency, unforeseen limitation.
- [ ] Style that only affects visually the compiled document
- [X] Addition that does not require change in the current structure.
- [ ] Enhancement that require changes to improve the format.

# Related Issues

# Dates when it got review approvals

# Release checklist

- [ ] Approved by at least two members of the committee?
- [ ] There were modifications after the review approvals? If so, please
      ask reviewers to update their review.
- [ ] Proponents and moderador should explicitly agree that it is ready to
      to merge.
- [ ] The moderador is the one in charge to actually merge or close this PR
      according to the final decision.

# For maintainers

- [ ] Update the moderator with a volunteer from the committee. It would be
      best to have one single moderator to guide and help this PR to move
      forward. It is OK to update the moderador pass it to another one.
- [ ] Confirm that the associated branch was deleted after the merging.
- [ ] Wrap-up and close the related issues.

# Comments

I just noticed that it was missing @emmerbodc  in the list of reviewers.

### CODE REVIEW

**Comment by castelao** [comment]
@vturpin , is Thierry Carval still active? If not, should we remove him from the reviewers's list so he stops receiving automatic alerts from every change here? Note that this is just an internal GitHub setup and has nothing to do with the document itself.

**Comment by vturpin** [comment]
Hi,@castelao, I just check with Thierry, he was about to answer but I'll do it on his behalf. He is sorry not being able to be active here. He is obviously very interested, but has no time to dedicate. 
So yes, please remove him from the reviewer list.

**Review by vturpin — APPROVED** [review]

**Comment by castelao** [comment]
@vturpin , thanks!

@tcarval , I'm sorry. I made a poor choice of words here, and in doing so I was quite rude. I remember hearing that someone retired over there and thought it could be you. What I actually wanted to ask was if you were interested in keep receiving this alerts. I believe that you should receive a notification email for every issue and pull request open here?! There is no actual downside in keeping you in 'reviewers list', but the opposite. Your knowledge and experience in this field is greatly appreciated. If you don't mind keep receiving the alert emails, I would just keep you in the list. If you prefer to be removed from that list, please let me know.

**Comment by tcarval** [comment]
> opposite

Hello Guilherme, yes I am very interested in OceanGliders activity, I wish I could be more active, please keep me in the loop 🙂

**Comment by castelao** [comment]
@tcarval , fantastic! Please, feel no pressure, and whenever you have a chance to participate, it will be much appreciated. Thanks!

**Comment by castelao** [comment]
@OceanGlidersCommunity/format-maintainers , do you agree in adding @emmerbodc in the reviewers list? She is listed as a core author and it would be helpful to have more people able to approve. Feel free to contact me by email if you want help on the procedure to approve it.

**Review by kerfoot — APPROVED** [review]
looks good to me.

**Pull request merged**
