### PR TITLE
File_Naming_Convention.adoc

### PR DESCRIPTION
**Pull request by vturpin**

### CODE REVIEW

**Comment by castelao** [comment]
I remember we discussed this issue more than once but I don't remember the final decision. Would you have the meeting notes? I think that there were opposing arguments. I believe that the standard used on IOOS is `sp022-2018...nc`. If that is correct, what would be the argument for '_'?

@kerfoot , could you confirm the standard that you use? Is it `sp022-2018...` or `sp022_2018...`? Thanks!

**Comment by vturpin** [comment]
"US IOOS" uses sp022-2018... 
I like this cascade approach: 
   + "trajectory" : "<platform_code>_<start_date>" (ex :  "sp065_20210616T1430")
   + "id" : "<trajectory>_<data_mode>" (ex : "sp065_20210616T1430_R")
   + "file_name" : "<id>.nc" (ex : "sp065_20210616T1430_R.nc")

I like to keep a coherence in the naming by '-' or '_' but not both.
Then, I have no strong opinion in using "_" vs "-", as I do not see high level impact.

**Comment by kerfoot** [comment]
US DAC uses:

glider-YYYYmmddTHHMM_rt.nc or glider-YYYYmmddTHHMM_delayed.nc

I originally used the - between the glider and the date in order to make pulling the glider name our of the filenames simple.  But that information is now stored in the file, so I'm ok with using either '-' or '_'.

**Review by justinbuck — APPROVED** [review]
I am agnostic on this so long as we are consistent

**Review by glidermann — APPROVED** [review]
Since no objection, keeping "_" and cascading naming system. Improved text for readability and grammar.

**Comment by soerenthomsen** [comment]
Seems like there is an agreement here or?

**Pull request merged**
