### PR TITLE
Add methodology section

### PR DESCRIPTION
**Pull request by callumrollo**
Proponents: 
Moderator: @OceanGlidersCommunity/format-mantainers

# Type of PR

- [x] Addition that does not require change in the current structure.

# Related Issues

#143 

# Release checklist

- [ ] Approved by at least two members of the committee?
- [ ] There were modifications after the review approvals? If so, please
      ask reviewers to update their review.
- [ ] Proponents and moderador should explicitly agree that it is ready to
      to merge.
- [ ] The moderador is the one in charge to actually merge or close this PR
      according to the final decision.

# For maintainers

- [ ] Update the moderator with a volunteer from the committee. It would be
      best to have one single moderator to guide and help this PR to move
      forward. It is OK to update the moderador pass it to another one.
- [ ] Confirm that the associated branch was deleted after the merging.
- [ ] Wrap-up and close the related issues.

### CODE REVIEW

**Comment by callumrollo** [comment]
This PR moves the history section to the history doc and adds a methodology section based on the text by @vturpin in #143

**Review by vturpin — APPROVED** [review]

**Review by glidermann — CHANGES_REQUESTED** [review]
There are a lot of problems with the English..I don't have time now though.

**Comment by callumrollo** [comment]
I've cleaned up the spelling and grammar @glidermann

**Review by vturpin — APPROVED** [review]

**Review by justinbuck — APPROVED** [review]
This is as per discussions in the OG 1.0 meetings

**Review by vturpin — APPROVED** [review]

**Comment by callumrollo** [comment]
@glidermann can you re-review this when you have time? Currently merging is blocked

**Review by glidermann — APPROVED** [review]

**Comment by glidermann** [comment]
The changes are fine...can someone remind me:   did we agree to keep the Endorsement section? I don't think it is necessary, and maybe not the right wording...they  participated and generally agreed with this effort, but have not seen and formally endorsed the final product.

**Comment by callumrollo** [comment]
Thanks for the quick review! The endorsement section was removed in #146

**Comment by glidermann** [comment]
Thanks...I was confused by the text in this branch I guess, just below this PR.

**Pull request merged**
