### PR TITLE
Add spray example nc and cdl files

### PR DESCRIPTION
**Pull request by jenseva**
First pass on files from spray, let me know if you have feedback!

Proponents: @jenseva 
Moderator: @OceanGlidersCommunity/format-mantainers

# Type of PR

- [ ] Typo without possible change of interpretation of the related text.
- [ ] Fix of some error, inconsistency, unforeseen limitation.
- [ ] Style that only affects visually the compiled document
- [ x] Addition that does not require change in the current structure.
- [ ] Enhancement that require changes to improve the format.

# Dates when it got review approvals

# Release checklist

- [ ] Approved by at least two members of the committee?
- [ ] There were modifications after the review approvals? If so, please
      ask reviewers to update their review.
- [ ] Proponents and moderador should explicitly agree that it is ready to
      to merge.
- [ ] The moderador is the one in charge to actually merge or close this PR
      according to the final decision.

# For maintainers

- [ ] Update the moderator with a volunteer from the committee. It would be
      best to have one single moderator to guide and help this PR to move
      forward. It is OK to update the moderador pass it to another one.
- [ ] Confirm that the associated branch was deleted after the merging.
- [ ] Wrap-up and close the related issues.

# Comments

### CODE REVIEW

**Review by vturpin — APPROVED** [review]

**Review by glidermann — APPROVED** [review]

**Comment by emmerbodc** [comment]
I ran through the format checker Gui sent and saw some missing variables, not sure if its not picking some of these because they are in lowercase.

**Comment by castelao** [comment]
> I ran through the format checker Gui sent and saw some missing variables, not sure if its not picking some of these because they are in lowercase.

@emmerbodc , that's a possibility. I haven't have the chance to update the checker to accept lowercase as well.

@jenseva , this is great. I appreciate all those metadata. It might be worth to truncate the data to reduce the file size since this is just an example. If you do so, I suggest adding a comment mentioning that. I do remember adding such a comment in the [sp041](https://github.com/OceanGlidersCommunity/OG-format-user-manual/blob/main/og_format_examples_files/sp041_20191205T1757_R.cdl) file, but it looks like that comment was removed.

**Comment by castelao** [comment]
> I ran through the format checker Gui sent and saw some missing variables, not sure if its not picking some of these because they are in lowercase.

@emmerbodc , it's a bug! I just checked it.  I'll fix that this Friday. Good catch!

**Comment by emmerbodc** [comment]
> > I ran through the format checker Gui sent and saw some missing variables, not sure if its not picking some of these because they are in lowercase.
> 
> @emmerbodc , it's a bug! I just checked it. I'll fix that this Friday. Good catch!

If we do allow both uppercase and lowercase for variables will this impact other generic tooling we create? For example ingesting to ERDDAP, GDAC onward flow? Just want to check any potential impacts, as in the manual we do specify them as uppercase. 

I can bring this up in today's meeting.

**Review by emmerbodc — CHANGES_REQUESTED** [review]
Following meeting discussion : 
reduce data cycles
keep this version for later review due to time pressures. 
upload a file with minimum mandatory variables

**Comment by jenseva** [comment]
Thanks all for taking a look at it!

I've reduced the file further, updated the id format and have added comments that the file is truncated. The file should have all the mandatory variables, please let me know if you have any more feedback.

**Review by emmerbodc — APPROVED** [review]
Thank you @jenseva

**Pull request merged**
