### PR TITLE
Build OG-Format

### PR DESCRIPTION
**Pull request by castelao**
Build the PDF to make it easier to review.

### CODE REVIEW

**Comment by soerenthomsen** [comment]
Thanks @castelao for preparing this. I am not an expert on GitHub actions but happy to approve this if needed to move on.

**Comment by glidermann** [comment]
oops my mistake, I clicked ready for review when trying to see what it was about...

**Comment by callumrollo** [comment]
Is the goal of this to auto-generate a pdf of the adoc? I'm trying to get the workflow to run, but it doesn't produce anything in its current iteration https://github.com/callumrollo/OG-format-user-manual/runs/7539280100?check_suite_focus=true

Making a human-readable doc for each PR would be great, and would really improve readability. As an alternative, could we include asciidoctor as a pre-commit? This would be simple to implement, but would place a bit more of a burden on contributors.

**Comment by vturpin** [comment]
+ Creating a pdf of the adoc is the goal (for the fixed version).
+ Making a human readable doc for each PR is certainly valuable to understand the impact on the final document.
Why including asciidoctor would put extra burden on contributors ?
How other repo in the OceanGlidersCommunity are doing ? Can we align with them ?

**Comment by callumrollo** [comment]
The other oceangliders repos are using a static site generator with jupyterbooks and some fairly complex CI to make a new version of the jupyterbooks for each PR. This toolchain is broken at the moment.

One quick and fairly simple solution would be to add a pre-commit hook that runs asciidoctor on each commit, creating a pdf that is then pushed with the other code changes. However, this requires people to install an use the pre-commit hook, hence the higher burden on contributors. pre-commit hooks are optional though, so people could just skip it. This is done at the user end, not on GitHub. I can set up an example to see if it would work

**Comment by callumrollo** [comment]
First draft at auto generating pdf using pre-commit

https://github.com/callumrollo/OG-format-user-manual/tree/callum-patch-2

@vturpin

**Comment by castelao** [comment]
This workflow now exports the OG format document into HTML and PDF, then upload it to https://oceangliderscommunity.github.io/OG-format-user-manual/

Unfortunately, to run it, we have to merge into the main branch first. If you trust me, I need two of you to approve this to show it working.

@callumrollo , thanks for your solution using pre-commit. I think that if this workflow here works, it will be easier for everyone and allow more contributions.

**Comment by callumrollo** [comment]
Much more elegant! I had wondered about using gh pages. Thanks Gui

**Review by callumrollo — APPROVED** [review]

**Review by vturpin — APPROVED** [review]

**Comment by castelao** [comment]
Thanks!

**Pull request merged**
