### PR TITLE
DEPLOYMENT_TIME.adoc

### PR DESCRIPTION
**Pull request by vturpin**

### CODE REVIEW

**Review by justinbuck — APPROVED** [review]

**Review by glidermann — APPROVED** [review]

**Comment by vturpin** [comment]
Hi all, I plan to merge this PR tomorrow if no other comment.
This is to use DEPLOYMENT_TIME (for coherence) following ISO 8601 : YYYY-MM-DDThh:mm:ss (instead of "DEPLOYMENT_DATE" without constrain on the format.

**Comment by vturpin** [comment]
Yes I was about to remove my previous comment when I saw yours related to this.
Let's continue the discussion then. I will not merge until we agree.

**Comment by vturpin** [comment]
My understanding of "DEPLOYMENT_TIME" is that it is a metadata collected by the operator when they deploy the glider. It is usually registered manually from the GPS on board of the ship.
It allows a rapid check of deployment coordinates without convertion. It has not to be extremely precise and must be human readable I think.

I understand the need to follow cf standard. But this infromation is not an axis, it is constant for the data set.

If using "DEPLOYMENT_TIME" constrain us to use the corresponding cf compliant unit "days since YYY-MM-DD:hhmmss" then I rather prefer using "DEPLOYMENT_DATE" under iso 8601.

**Comment by castelao** [comment]
I don't have a strong opinion on this one, but I'm slightly inclined to use time as double with days since... and by doing that be more machine friendly and easier to automate.

**Comment by glidermann** [comment]
I tend to agree with Victor on this one after understanding a bit better. I think machines could just read TIME(1) and humans can read DEPLOYMENT_DATE when browsing or sorting. It's also easier to enter (expected to be entered by humans).

**Review by castelao — CHANGES_REQUESTED** [review]
I think that the trajectory name follow a convention based on the deployment time/date, right? It's not ISO but easily human readable without even requiring to open the file itself. That convention could partially address the issue here.

I do have empathy with the idea to be easy to (human) read and check on the field, but once it reaches the stage of a netCDF, it is not human readable by itself anymore, which means that we have to use some parser to decode the file. I think we would do better improving our tools to provide that easily for us. For instance, xarray already does that automatically for us showing a human readable print. Also, we shouldn't rely on manual verification, but automatic checks able to process large number of files efficiently.

I developed an opinion. My vote is on using `DEPLOYMENT_TIME` with the CF time standard (days since) using a real instead of a double to reduce the size on the file. If anyone else think it is better to have it as a string, I'm fine to drop my vote and let it go.

**Review by castelao — APPROVED** [review]

**Review by justinbuck — APPROVED** [review]

**Pull request merged**
