### PR TITLE
Remove dimension N_SENSOR and N_PARAM.adoc

### PR DESCRIPTION
**Pull request by vturpin**
Remove both dimension and adapt the doc to this changes. Remove the PARAMETER's information section that is becoming unecessary and redondant with PARAM attributes and SENSOR attributes Create empty and dimensionless SENSOR variable with attribute describing the sensor. Adjust text a little bit.

Proponents: 
Moderator: @OceanGlidersCommunity/format-mantainers

# Type of PR

- [x] Addition that does not require change in the current structure.
- [x] Enhancement that require changes to improve the format.

# Related Issues
#184 

# comment
This PR is not 100% align with Emma's cdl but I think it is improving the format, simplying it and avoiding redondancies (ex. units)

### CODE REVIEW

**Comment by vturpin** [comment]
This is the latest major change in the format, appart from our final review.

**Review by callumrollo — APPROVED** [review]

**Comment by vturpin** [comment]
also related to #109

**Comment by vturpin** [comment]
@emmerbodc would be nice to have your opinion on this one before merging.

We can also merge it now and review it during our next meeting on Monday. It may facilitate progress.

**Comment by emmerbodc** [comment]
> @emmerbodc would be nice to have your opinion on this one before merging.
> 
> We can also merge it now and review it during our next meeting on Monday. It may facilitate progress.

Yes happy to merge and review in manual review meeting as will be easier to see changes.

**Pull request merged**
