### PR TITLE
add acknowledgements section

### PR DESCRIPTION
**Pull request by callumrollo**
This adds an acknowledgement section following the recomendation of @glidermann in #148. Work in progress, will clean up in the next few days

- [x] Style that only affects visually the compiled document

### CODE REVIEW

**Comment by castelao** [comment]
I missed this before. I think it is a great addition and I'm in favor of moving this forward. Please add GOMO to the list, since it supported me at that time.

**Comment by castelao** [comment]
@callumrollo @glidermann , this is still a draft. Is it ready for review? We can always add/edit later.

**Review by castelao — APPROVED** [review]
Looks good to me. Thank you!

**Review by vturpin — APPROVED** [review]
Look good to me too !

**Review by glidermann — COMMENTED** [review]
I am sorry to change things, but a minor request: can we please include EMODnet Physics to list of supporters?

**Pull request merged**
