### PR TITLE
Change ICES CODE "long name" attribute

### PR DESCRIPTION
**Pull request by vturpin**
Move from long name "ices code" to "ices code of the glider" to make it clearer that we are not talking about the ices code of the ship used to deploy the glider. Following #83 suggestion

Proponents: 
Moderator: @OceanGlidersCommunity/format-mantainers

# Type of PR

- [ ] Typo without possible change of interpretation of the related text.
- [ ] Fix of some error, inconsistency, unforeseen limitation.
- [ ] Style that only affects visually the compiled document
- [X] Addition that does not require change in the current structure.
- [ ] Enhancement that require changes to improve the format.

# Related Issues

# Dates when it got review approvals

#83 pushed 2 months ago. No comment since. So I push this PR.

# Release checklist

- [ ] Approved by at least two members of the committee?
- [ ] There were modifications after the review approvals? If so, please
      ask reviewers to update their review.
- [ ] Proponents and moderador should explicitly agree that it is ready to
      to merge.
- [ ] The moderador is the one in charge to actually merge or close this PR
      according to the final decision.

# For maintainers

- [ ] Update the moderator with a volunteer from the committee. It would be
      best to have one single moderator to guide and help this PR to move
      forward. It is OK to update the moderador pass it to another one.
- [ ] Confirm that the associated branch was deleted after the merging.
- [ ] Wrap-up and close the related issues.

# Comments

### CODE REVIEW

**Review by castelao — APPROVED** [review]
Sounds good. Better be explicit.

**Comment by castelao** [comment]
@justinbuck , could that leave room for confusion with a vessel collecting validating/calibrating measurements simultaneous to the glider? I don't have a strong opinion here.

**Comment by vturpin** [comment]
Why not "ices code of the glider" ?

**Comment by castelao** [comment]
@bodcmahe raised a comment on the related issue. I'm quoting here so we don't miss it.

"Sensible suggestion Victor. Perhaps even 'ICES platform code of the glider' to avoid ambiguity completely - ICES manage various vocabularies. Just a thought..."

Thanks Mark!

**Review by callumrollo — APPROVED** [review]

**Review by justinbuck — APPROVED** [review]
Approved by consensus at OG 1.0 meeting 24th April 2023

**Pull request merged**
